steps:
- name: 'sglahn/platformio-core:4.3.1'
  dir: .
  args: ['run']  
artifacts: 
  objects: 
    location: 'gs://$PROJECT_ID-firmwares/$TAG_NAME'
    paths: ['/workspace/.pio/build/tinypico/firmware.bin']
